name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Install WDACConfig module
      shell: powershell
      run: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module -Name WDACConfig -Force
    - name: Create WDAC Deny Configuration
      shell: powershell
      run: |
        New-DenyWDACConfig -drivers -PolicyName "LOLDrivers Deny" -ScanLocations .\drivers\
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./detections/wdac/*.xml
