name: Test Drivers

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  test-drivers:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Clean up test services before testing
      shell: powershell
      run: |
        $servicesToDelete = Get-Service | Where-Object { $_.Name -like "DriverTest*" } | Select-Object -ExpandProperty Name
        foreach ($serviceName in $servicesToDelete) {
            while ((Get-Service -Name $serviceName -ErrorAction SilentlyContinue).Status -ne $null) {
                Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
                sc.exe delete $serviceName
                Start-Sleep -Seconds 1
            }
        }
    - name: Test drivers
      shell: powershell
      run: |
        $logName = 'Microsoft-Windows-CodeIntegrity/Operational'
        $log = New-Object System.Diagnostics.Eventing.Reader.EventLogConfiguration $logName
        $log.MaximumSizeInBytes = '50000000'
        $log.IsEnabled = $true
        $log.SaveChanges()
        $i = 0
        (Get-ChildItem .\drivers\).FullName | ForEach-Object {
          $serviceName = "DriverTest$i"
          New-Service -BinaryPathName $_ -Name $serviceName -Description $_ -StartupType Manual
          Start-Service -Name $serviceName -ErrorAction SilentlyContinue
          $i++
        }
        $ScriptBlock = {
          foreach ($event in Get-WinEvent -FilterHashtable @{LogName = 'Microsoft-Windows-CodeIntegrity/Operational'; ID = 3077 } -ErrorAction SilentlyContinue ) {
            $xml = [xml]$event.toxml()
            $xml.event.eventdata.data | ForEach-Object { $hash = @{} } { $hash[$_.name] = $_.'#text' } { [pscustomobject]$hash } |
            Select-Object -Property 'SHA256 Hash' , 'File Name', 'OriginalFileName', 'ProductName', 'InternalName', 'FileDescription', 'FileVersion', 'SHA1 Hash', 'USN'
          }        
        }
        $Results = Invoke-Command -ScriptBlock $ScriptBlock
        $outputPath = ".\detections\wdac\TestResults.txt"
        $outputDirectory = Split-Path -Path $outputPath -Parent
        if (!(Test-Path -Path $outputDirectory)) {
          New-Item -ItemType Directory -Path $outputDirectory -Force
        }
        $Results | Out-File -FilePath $outputPath
    - name: List wdac directory
      shell: pwsh
      run: |
        Get-ChildItem -Path ./detections/wdac/
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: ./detections/wdac/TestResults.txt
