name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Check PowerShell version
      shell: pwsh
      run: |
        Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"
    - name: Confirm WDACConfig Installation
      shell: pwsh
      run: |
        if (-not (Get-Module -Name WDACConfig -ListAvailable)) {
            Write-Host "WDACConfig module not found. Installing..."
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
            Install-Module -Name WDACConfig -Force
            Write-Host "WDACConfig module installed successfully."
        } else {
            Write-Host "WDACConfig module is already installed."
        }

    - name: Create WDAC Deny Configuration
      shell: pwsh
      run: |
        try {
            New-DenyWDACConfig -drivers -PolicyName "LOLDriversDeny" -ScanLocations .\drivers\
        } catch {
            Write-Output $_.Exception.Message
            Write-Output $_.Exception.StackTrace
            exit 1
        }
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./*.xml
    - name: Move XML to detections directory
      shell: pwsh
      run: |
        if (!(Test-Path -Path ./detections/wdac/)) {
            New-Item -ItemType Directory -Path ./detections/wdac/
        }
        Move-Item -Path ./*.xml -Destination ./detections/wdac/
    - name: Commit Generated Data
      run: |     
          git config --global user.name "Github Actions"
          git config --global user.email "robot@noreply.github.com"
          git config --global push.default simple
          git add ./detections/wdac/
          git commit -m "New WDAC Policy Created [ci skip]"
          git push origin HEAD:${{ github.ref }} -f
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
