name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Create audit policy
      shell: powershell
      run: |
        if(!(Test-Path -Path .\detections\wdac\)){
          New-Item -ItemType Directory -Path .\detections\wdac\ -Force
        }
        Get-ChildItem .\drivers\*.bin | Rename-Item -newname { $_.name -replace '.bin','.sys' };
        $drivers = Get-SystemDriver -ScanPath .\drivers\ -NoShadowCopy;
        $NewDriverRules = New-CIPolicyRule -DriverFiles $drivers -Level Hash -Audit;
        Merge-CIPolicy -OutputFilePath .\detections\wdac\AuditPolicy.xml -PolicyPaths C:\Windows\schemas\CodeIntegrity\ExamplePolicies\AllowAll.xml -Rules $NewDriverRules | Out-Null;
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./detections/wdac/*.xml
