name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Check PowerShell version
      shell: pwsh
      run: |
        Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"
    - name: List drivers directory
      shell: pwsh
      run: |
        Get-ChildItem -Path .\drivers\
    - name: Create WDAC Deny Configuration
      shell: pwsh
      run: |
        try {
            New-DenyWDACConfig -drivers -PolicyName "LOLDriversDeny" -ScanLocations .\drivers\
        } catch {
            Write-Output $_.Exception.Message
            Write-Output $_.Exception.StackTrace
            exit 1
        }
    - name: List current directory
      shell: pwsh
      run: |
        Get-ChildItem -Path ./
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./*.xml
    - name: Move XML to detections directory
      shell: pwsh
      run: |
        if (!(Test-Path -Path ./detections/wdac/)) {
            New-Item -ItemType Directory -Path ./detections/wdac/
        }
        Move-Item -Path ./*.xml -Destination ./detections/wdac/
    - name: Test drivers
      shell: powershell
      run: |
        $i = 0
        (Get-ChildItem .\drivers\).FullName | ForEach-Object {
          New-Service -BinaryPathName $_ -Name "DriverTest$i" -Description $_ -StartupType Manual
          Start-Service -Name "DriverTest$i" -ErrorAction SilentlyContinue
          $i++
        }
        $logName = 'Microsoft-Windows-CodeIntegrity/Operational'
        $log = New-Object System.Diagnostics.Eventing.Reader.EventLogConfiguration $logName
        $log.MaximumSizeInBytes = '50000000'
        $log.IsEnabled = $true
        $log.SaveChanges()
        $ScriptBlock = {
          foreach ($event in Get-WinEvent -FilterHashtable @{LogName = 'Microsoft-Windows-CodeIntegrity/Operational'; ID = 3077 } -ErrorAction SilentlyContinue ) {
            $xml = [xml]$event.toxml()
            $xml.event.eventdata.data | ForEach-Object { $hash = @{} } { $hash[$_.name] = $_.'#text' } { [pscustomobject]$hash } |
            Select-Object -Property 'SHA256 Hash' , 'File Name', 'OriginalFileName', 'ProductName', 'InternalName', 'FileDescription', 'FileVersion', 'SHA1 Hash', 'USN'
          }        
        }
        $Results = Invoke-Command -ScriptBlock $ScriptBlock
        $Results 
        $Results | Out-File -FilePath .\detections\wdac\TestResults.txt
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: ./detections/wdac/TestResults.txt
