name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Check PowerShell version
      shell: pwsh
      run: |
        Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"
    - name: List drivers directory
      shell: pwsh
      run: |
        Get-ChildItem -Path .\drivers\
    - name: Create WDAC Deny Configuration
      shell: pwsh
      run: |
        # Get the module path
        $modulePath = (Get-Module -Name WDACConfig -ListAvailable).ModuleBase

        # Construct the path to the Resources.ps1 file
        $resourcesFilePath = Join-Path -Path $modulePath -ChildPath 'Resources.ps1'

        # Load the script content into a variable
        $scriptContent = Get-Content -Path $resourcesFilePath -Raw

        # Remove the undesired line
        $scriptContent = $scriptContent -replace 'if \(-NOT \(\[System\.Environment\]::OSVersion\.Version -ge ''10\.0\.22621''\)\) { Write-Error -Message "You''re not using Windows 11 22H2, exitting\.\.\." }', ''

        # Save the modified content back to the file
        $scriptContent | Set-Content -Path $resourcesFilePath

        try {
            New-DenyWDACConfig -drivers -PolicyName "LOLDrivers Deny" -ScanLocations .\drivers\
        } catch {
            Write-Output $_.Exception.Message
            Write-Output $_.Exception.StackTrace
            exit 1
        }
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./detections/wdac/*.xml
