name: Generate WDAC Policies

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main, test-branch]

jobs:
  generate-wdac:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
        lfs: true
    - name: Check PowerShell version
      shell: pwsh
      run: |
        Write-Output "PowerShell version: $($PSVersionTable.PSVersion)"
    - name: List drivers directory
      shell: pwsh
      run: |
        Get-ChildItem -Path .\drivers\
    - name: Create WDAC Deny Configuration
      shell: pwsh
      run: |
        try {
            New-DenyWDACConfig -drivers -PolicyName "LOLDriversDeny" -ScanLocations .\drivers\
        } catch {
            Write-Output $_.Exception.Message
            Write-Output $_.Exception.StackTrace
            exit 1
        }
    - name: List policy directory
      shell: pwsh
      run: |
        Get-ChildItem -Path ./detections/wdac/
    - name: List current directory
      shell: pwsh
      run: |
        Get-ChildItem -Path ./

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WDAC Policies
        path: ./*.xml
